INSERT INTO tipps (tipp) VALUES ('Cornflakes nicht mit dem Löffel, sondern mit der Gabel essen ... spart garantiert jede Menge Milch.');
INSERT INTO tipps (tipp) VALUES ('Briefe nicht frankieren und als Absender den Empfänger eintragen ... ist gleich eine kostenlose „Rücksendung zum Empfänger“.');
INSERT INTO tipps (tipp) VALUES ('Teebeutel immer zweimal verwenden ... wenn man nicht zu lange wartet, geht auch noch ein drittes Mal.');
INSERT INTO tipps (tipp) VALUES ('Schwäbische Schorle trinken ... ein halbes Glas Sprudelwasser und ein halbes Glas Leitungswasser.');
INSERT INTO tipps (tipp) VALUES ('Möglichst lange ausschlafen ... damit man sich das Frühstück sparen kann.');
INSERT INTO tipps (tipp) VALUES ('Flüssigseife immer wieder verdünnen ... mit Wasser.');
INSERT INTO tipps (tipp) VALUES ('Weniger duschen ... denn schon Winfried Kretschmann riet: „Auch der Waschlappen ist eine brauchbare Erfindung.“');
INSERT INTO tipps (tipp) VALUES ('GESCHENKE VON ANDEREN SCHENKEN LASSEN Wenn sich das Kind etwas Teures wünscht, gleich den Großeltern oder der Tante als Geschenke-Tipp weitergeben.');
INSERT INTO tipps (tipp) VALUES ('MUSS DAS WIRKLICH IN DIE WÄSCHE? Sweater oder Pulli riechen nach einer Nacht auf dem Balkon wieder frisch');
INSERT INTO tipps (tipp) VALUES ('Altes Brot als Pizzaboden verwenden Spart nicht nur Geld für frischen Teig, sondern gibt auch altem Brot eine neue Bestimmung. Einfach mit Tomatensauce bestreichen, belegen und backen. Schwäbische Nachhaltigkeit pur.');
INSERT INTO tipps (tipp) VALUES ('Socken als Staubtücher benutzen Bevor man alte Socken wegwirft, können sie ein zweites Leben als Staubtücher führen. Passt hervorragend zur schwäbischen Devise: "Nix verschwenda!"');
INSERT INTO tipps (tipp) VALUES ('Zahnpastatuben aufschneiden Um wirklich alles aus der Zahnpastatube herauszubekommen, einfach aufschneiden. So findet man oft noch Zahnpasta für mehrere Tage.');
INSERT INTO tipps (tipp) VALUES ('Kaffeesatz als Dünger Anstatt Kaffeesatz wegzuwerfen, kann man ihn als Dünger für Pflanzen verwenden. Das spart nicht nur Dünger, sondern macht auch den Garten schwäbisch grün.');
INSERT INTO tipps (tipp) VALUES ('Mehrwegflaschen als Deko Leere Wein- oder Bierflaschen müssen nicht im Glascontainer landen. Sie lassen sich wunderbar als Vasen oder Kerzenhalter wiederverwenden.');
INSERT INTO tipps (tipp) VALUES ('Kleiderbügel aus Draht als Grillzange Wer braucht schon teure Grillzangen, wenn ein alter Kleiderbügel genau denselben Zweck erfüllt? Einfach zurechtbiegen und schon hat man schwäbische Ingenieurskunst am Grill.');
INSERT INTO tipps (tipp) VALUES ('Eiswürfelbeutel als Frischhaltebeutel Nach dem Gebrauch die Eiswürfelbeutel nicht wegwerfen, sondern auswaschen und als Frischhaltebeutel für Kräuter oder Gemüsereste nutzen.');
INSERT INTO tipps (tipp) VALUES ('Duschhauben als Schüsselabdeckung Kostenlose Duschhauben aus Hotels sind nicht nur fürs Haar gedacht. Sie eignen sich auch hervorragend, um Schüsseln mit Resten abzudecken.');
INSERT INTO tipps (tipp) VALUES ('Klopapier zweimal benutzen: Einmal zum Abwischen und einmal zum Polieren.');
INSERT INTO tipps (tipp) VALUES ('Zahnbürste: Nur die Spitze benutzen: Der Rest ist nur Dekoration.');
INSERT INTO tipps (tipp) VALUES ('Schraubenzieher: Kann man auch als Nagellackentferner benutzen.');
INSERT INTO tipps (tipp) VALUES ('Heizung im Winter auslassen: Einfach einen Pullover anziehen.');
INSERT INTO tipps (tipp) VALUES ('Zum Schwimmen gehen: In den See oder Fluss – das Meer ist viel zu teuer.');
INSERT INTO tipps (tipp) VALUES ('Statt Taxi oder Bus: Einfach zu Fuß gehen – ist gesünder und spart Geld. Der Fußbus fährt immer.');
INSERT INTO tipps (tipp) VALUES ('Beim Restaurantbesuch: Immer nur Wasser trinken – das ist kostenlos.');
INSERT INTO tipps (tipp) VALUES ('Urlaubsreisen: Warum in die Ferne schweifen? Das Gute liegt so nah!');
INSERT INTO tipps (tipp) VALUES ('Kaputte Glühbirnen nicht wegwerfen: Einfach mit etwas Klebeband reparieren.');
INSERT INTO tipps (tipp) VALUES ('Geschenkpapier bügeln und wiederverwenden Nach Geburtstagen oder Weihnachten das benutzte Geschenkpapier sorgfältig glätten und bügeln, um es für das nächste Geschenk wiederzuverwenden. Schwäbische Nachhaltigkeit und Sparsamkeit in Perfektion.');
INSERT INTO tipps (tipp) VALUES ('Alufolie als Backpapier-Ersatz Statt jedes Mal neues Backpapier zu kaufen, kann man Alufolie verwenden und diese nach Gebrauch einfach sauber wischen und wiederverwenden.');
INSERT INTO tipps (tipp) VALUES ('Leere Marmeladengläser als Trinkgläser oder Aufbewahrung Anstatt neue Gläser zu kaufen, können leere Marmeladengläser gereinigt und als Trinkgläser oder zur Aufbewahrung von kleinen Gegenständen genutzt werden.');
INSERT INTO tipps (tipp) VALUES ('Handy statt Postkarte Beim Urlaub spart man sich das Geld für Postkarten und das Porto, indem man stattdessen ein Foto mit dem Handy macht und dieses digital versendet.');
INSERT INTO tipps (tipp) VALUES ('Statt Deo: Einfach ein paar Zwiebelscheiben unter die Achseln klemmen.');
INSERT INTO tipps (tipp) VALUES ('Zum Kaffee trinken: Einfach den Kaffeesatz aus dem Vortag nochmal aufbrühen.');
INSERT INTO tipps (tipp) VALUES ('Öffentliche WLANs nutzen: Spart mobiles Datenvolumen.');
INSERT INTO tipps (tipp) VALUES ('Im Restaurant immer nur Wasser trinken und vom Brot des Nachbarn naschen. (Nicht empfehlenswert!)');
INSERT INTO tipps (tipp) VALUES ('Beim Geburtstagsgeschenk für den Chef "krank" melden und im nächsten Jahr dafür etwas Teureres schenken. (Vorsicht, kann nach hinten losgehen!)');
INSERT INTO tipps (tipp) VALUES ('Nur bei Vollmond nachts duschen Das spart nicht nur Wasser und Strom, sondern man kann auch die natürliche Mondhelligkeit nutzen, um den Weg ins Bad zu finden.');
INSERT INTO tipps (tipp) VALUES ('Socken als Kaffee-Filter benutzen Warum Geld für Kaffeefilter ausgeben, wenn die alten Socken genau denselben Zweck erfüllen können? Natürlich nur die sauberen!');
INSERT INTO tipps (tipp) VALUES ('Fernseher aus dem Fenster zeigen, um die Nachbarn mitzubeleuchten Warum sollte man alleine fernsehen, wenn die ganze Nachbarschaft profitieren kann? Spart Unterhaltungskosten und fördert die Gemeinschaft.');
INSERT INTO tipps (tipp) VALUES ('Haustiere als biologische Rasenmäher Wer braucht schon einen Rasenmäher, wenn man ein paar Ziegen im Garten halten kann? Spart Benzin und man bekommt kostenlosen Dünger dazu.');
INSERT INTO tipps (tipp) VALUES ('Pflastersteine als persönliches Fitnessgerät Statt teure Hanteln zu kaufen, einfach ein paar Pflastersteine aus dem Garten für das Heimtraining nutzen. Schwäbische Kreativität kennt keine Grenzen!');
INSERT INTO tipps (tipp) VALUES ('Einweggeschirr nur auf einer Seite benutzen Nach dem Essen einfach das Papptellerchen umdrehen und auf der anderen Seite für die nächste Mahlzeit verwenden. Spart Abwasch und Geld.');
INSERT INTO tipps (tipp) VALUES ('Mit dem Fahrrad durch die Waschanlage Warum für die Fahrradreinigung bezahlen, wenn man einfach durch die nächste Auto-Waschanlage radeln kann? Schnell, effizient und erfrischend.');
INSERT INTO tipps (tipp) VALUES ('Schrumpfschlauch als Kleidung Statt teure Kleidung zu kaufen, einfach in einen Schrumpfschlauch schlüpfen und erwärmen. Passt immer perfekt und ist ein echter Hingucker.');
INSERT INTO tipps (tipp) VALUES ('Gebrauchte Teebeutel als Duftbäumchen Einfach den gebrauchten Teebeutel im Auto aufhängen. Je nach Teesorte kann man so den Wagen mit einem Hauch von Earl Grey oder Pfefferminz erfrischen.');
INSERT INTO tipps (tipp) VALUES ('Lachen als Heizung Warum die Heizung anschalten, wenn man sich einfach mit Freunden treffen und so viel lachen kann, dass einem warm wird? Spart Heizkosten und stärkt die sozialen Bindungen.');
INSERT INTO tipps (tipp) VALUES ('WLAN-Signal mit Alufolie verstärken Einfach eine Alufolienkugel hinter den Router legen. Spart das Geld für einen teuren Signalverstärker und sorgt gleichzeitig für interessante Gespräche über die neue "Kunstinstallation" zu Hause.');
INSERT INTO tipps (tipp) VALUES ('Kleidung im Backofen trocknen Wer braucht schon einen Trockner, wenn der Backofen nach dem Sonntagsbraten noch warm ist? Spart Strom und gibt der Kleidung einen einzigartigen Duft.');
INSERT INTO tipps (tipp) VALUES ('Essensreste als exklusive Hautpflege Warum teure Kosmetikprodukte kaufen, wenn das Abendessen Gurkenscheiben für die Augen und Olivenöl für die Haut bietet? Spart Geld und ist 100% natürlich.');
INSERT INTO tipps (tipp) VALUES ('Staubsauger als Haustrockner Nach einem regnerischen Spaziergang den Staubsaugerbeutel entfernen und den Schlauch zum Trocknen von nassen Schuhen oder Kleidung verwenden. Spart Zeit und Energie.');
INSERT INTO tipps (tipp) VALUES ('Briefmarkenlecken als Sprachkurs Statt teure Sprachkurse zu buchen, einfach internationale Briefmarken sammeln und durch das Lecken der Rückseite Sprachen lernen. Spart Geld und erweitert den Horizont.');
INSERT INTO tipps (tipp) VALUES ('Zimmerpflanzen als persönliche Sauerstoffflaschen. Warum in die Berge fahren für frische Luft, wenn man einfach mehr Zimmerpflanzen anschaffen kann? Spart Reisekosten und verbessert die Raumluft.');
INSERT INTO tipps (tipp) VALUES ('Alte Zeitungen als Tapeten Statt teure Tapeten zu kaufen, kann man die Wände einfach mit alten Zeitungen tapezieren. Spart Geld und bietet gleichzeitig Leseunterhaltung für Jahre.');
INSERT INTO tipps (tipp) VALUES ('Geburtstage in Schaltjahren feiern Geburtstag nur alle vier Jahre zu feiern spart nicht nur bei den Feierlichkeiten, sondern hält auch jung. Wer kann schon behaupten, erst 15 zu sein, wenn er in Wirklichkeit 60 ist?');
INSERT INTO tipps (tipp) VALUES ('Salzstreuer mit einem Loch Um den Salzverbrauch zu reduzieren, einfach alle bis auf ein Loch am Salzstreuer zukleben. Spart Salz und fördert eine gesündere Ernährung.');
INSERT INTO tipps (tipp) VALUES ('Die Kunst des "Borrow-Shopping" Warum kaufen, wenn man sich alles von Freunden und Nachbarn leihen kann? Nicht nur sparsam, sondern fördert auch die Gemeinschaft – solange man sich irgendwann auch mal revanchiert.');
INSERT INTO tipps (tipp) VALUES ('Müllbeutel als Regenmantel Ein Loch für den Kopf und zwei für die Arme in einen großen Müllbeutel schneiden – voilà, ein wasserdichter Regenmantel. Spart Geld und ist ein modisches Statement.');
INSERT INTO tipps (tipp) VALUES ('Geschirrspülen beim Duschen Warum Zeit und Wasser verschwenden, indem man Geschirr und sich selbst separat reinigt? Einfach Teller und Besteck mit in die Dusche nehmen. Spart Wasser und Zeit.');
INSERT INTO tipps (tipp) VALUES ('Cornflakes nicht mit dem Löffel, sondern mit der Gabel essen ... spart garantiert jede Menge Milch.');
INSERT INTO tipps (tipp) VALUES ('Briefe nicht frankieren und als Absender den Empfänger eintragen ... ist gleich eine kostenlose „Rücksendung zum Empfänger“.');
INSERT INTO tipps (tipp) VALUES ('Teebeutel immer zweimal verwenden ... wenn man nicht zu lange wartet, geht auch noch ein drittes Mal.');
INSERT INTO tipps (tipp) VALUES ('Schwäbische Schorle trinken ... ein halbes Glas Sprudelwasser und ein halbes Glas Leitungswasser.');
INSERT INTO tipps (tipp) VALUES ('Möglichst lange ausschlafen ... damit man sich das Frühstück sparen kann.');
INSERT INTO tipps (tipp) VALUES ('Flüssigseife immer wieder verdünnen ... mit Wasser.');
INSERT INTO tipps (tipp) VALUES ('Weniger duschen ... denn schon Winfried Kretschmann riet: „Auch der Waschlappen ist eine brauchbare Erfindung.“');
INSERT INTO tipps (tipp) VALUES ('GESCHENKE VON ANDEREN SCHENKEN LASSEN Wenn sich das Kind etwas Teures wünscht, gleich den Großeltern oder der Tante als Geschenke-Tipp weitergeben.');
INSERT INTO tipps (tipp) VALUES ('MUSS DAS WIRKLICH IN DIE WÄSCHE? Sweater oder Pulli riechen nach einer Nacht auf dem Balkon wieder frisch Altes Brot als Pizzaboden verwenden');
INSERT INTO tipps (tipp) VALUES ('"Drive-In" im eigenen Garten Ein weißes Laken als Leinwand und den Beamer aus dem Büro ausleihen, um einen Filmabend unter freiem Himmel zu genießen. Spart Kinokosten und das Popcorn ist auch günstiger.');
INSERT INTO tipps (tipp) VALUES ('Katze als Staubwedel Mit einem freundlichen Streicheln über Möbel und Regale wird die Katze zum lebenden Staubwedel. Spart den Kauf von Staubtüchern und die Katze genießt die Aufmerksamkeit.');
INSERT INTO tipps (tipp) VALUES ('Doppelter Nutzen von Kondenswasser Das Kondenswasser der Klimaanlage oder des Wäschetrockners auffangen und für das Gießen der Pflanzen verwenden. Spart Wasser und ist umweltfreundlich.');
INSERT INTO tipps (tipp) VALUES ('Eierkartons als Schuhregal Alte Eierkartons bieten die perfekte Größe, um Schuhe ordentlich zu verstauen. Spart Geld für ein Schuhregal und recycelt gleichzeitig.');
INSERT INTO tipps (tipp) VALUES ('Alte CDs als Vogelscheuchen Die reflektierende Oberfläche alter CDs kann im Garten als Vogelscheuche dienen. Spart den Kauf einer Vogelscheuche und gibt den CDs eine neue Bestimmung.');
INSERT INTO tipps (tipp) VALUES ('Urlaubsfotos als Fensterdekoration Statt teurer Gardinen oder Vorhänge, einfach Urlaubsfotos vergrößern und ans Fenster hängen. Spart Geld und hält die Erinnerungen lebendig.');

INSERT INTO savingGoals (name, goalamount) VALUES ('Auto',1000);
INSERT INTO savingGoals (name, goalamount) VALUES ('Haus',500);

INSERT INTO expenses (name, amount, assignment) VALUES ('Overwatch Skins', 150, 1);
INSERT INTO expenses (name, amount, assignment) VALUES ('Fortnite Skins', 90, 2);